import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Header from "../components/header/Header";
import Hero from "../components/Hero/Hero";

export default function Home(results) {
  return (
    <div className="bg-[#ffffff]  pt-4 md:pt-6 h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-screen-lg mx-auto">
        <Header />
        <Hero />
      </main>
    </div>
  );
}
